name: Test1
on:
  - push

jobs:
  foo:
    name: Foo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-16.04
          - ubuntu-18.04
          - windows-2019
    steps:
      - name: step1
